/*
 * <license>
 * The contents of this file are subject to the Mozilla Public License 
 * Version 1.1 (the "License"); you may not use this file except in 
 * compliance with the License.  You may obtain a copy of the License 
 * at http://www.mozilla.org/MPL/
 * 
 * Software distributed under the License is distributed on an 
 * "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or 
 * implied. See the License for the specific language governing rights 
 * and limitations under the License.
 * 
 * The Original Code is Web Photo Publisher.
 * 
 * The Initial Developer of the Original Code is Mark Roth.  Portions 
 * created by Mark Roth are Copyright (C) 2003 Mark Roth.  
 * All Rights Reserved.
 * 
 * Contributor(s) listed below.
 * </license>
 */

package com.javaimagealbum;

/**
 * Introduces the user to the program
 *
 * @author  Mark Roth
 * @author  Mirko Actis
 */
public class IntroPanel 
    extends javax.swing.JPanel 
    implements WizardPanel
{

    /** Creates new form IntroPanel */
    public IntroPanel() {
        initComponents ();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        tpDescription = new javax.swing.JTextPane();
        pnlTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        pnlBottom = new javax.swing.JPanel();
        cbSkipIntro = new javax.swing.JCheckBox();

        setLayout(new java.awt.BorderLayout());

        setBackground(java.awt.Color.white);
        tpDescription.setEditable(false);
        tpDescription.setFont(new java.awt.Font("SansSerif", 0, 12));
        tpDescription.setText("This program will guide you through the process of publishing your photographs to the web.  The result will be a directory with .html and .jpg / .gif files that you can upload to your current web host.\n\nPress the next button below and follow the steps on each screen.\n\nTo know about new release of this program please go to:\n\nhttp://javaimagealbum.berlios.de");
        add(tpDescription, java.awt.BorderLayout.CENTER);

        pnlTitle.setLayout(new javax.swing.BoxLayout(pnlTitle, javax.swing.BoxLayout.Y_AXIS));

        pnlTitle.setBackground(java.awt.Color.white);
        lblTitle.setFont(new java.awt.Font("SansSerif", 1, 14));
        lblTitle.setForeground(new java.awt.Color(0, 153, 153));
        lblTitle.setText("Java Image Album");
        lblTitle.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(3, 3, 3, 3)));
        pnlTitle.add(lblTitle);

        add(pnlTitle, java.awt.BorderLayout.NORTH);

        pnlBottom.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        pnlBottom.setBackground(java.awt.Color.white);
        cbSkipIntro.setBackground(java.awt.Color.white);
        cbSkipIntro.setFont(new java.awt.Font("SansSerif", 0, 12));
        cbSkipIntro.setMnemonic('d');
        cbSkipIntro.setText("Don't Show Intro Panel Next Time");
        cbSkipIntro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSkipIntroActionPerformed(evt);
            }
        });

        pnlBottom.add(cbSkipIntro);

        add(pnlBottom, java.awt.BorderLayout.SOUTH);

    }
    // </editor-fold>//GEN-END:initComponents

    private void cbSkipIntroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSkipIntroActionPerformed
        Settings.getInstance().setProperty( Constants.SKIP_INTRO, 
            "" + cbSkipIntro.isSelected() );
    }//GEN-LAST:event_cbSkipIntroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbSkipIntro;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlBottom;
    private javax.swing.JPanel pnlTitle;
    private javax.swing.JTextPane tpDescription;
    // End of variables declaration//GEN-END:variables

    /** Returns true if all required data was filled in for this panel.
     */
    public boolean isSatisfied() {
        return true;
    }

    /** Called when the panel is shown to the user
     */
    public void showPanel() {
    }

    /** Called when the panel is hidden from the user
     */
    public void hidePanel(boolean forwardDirection) throws CannotChangePanelException {
    }
}
