/*
 * <license>
 * The contents of this file are subject to the Mozilla Public License 
 * Version 1.1 (the "License"); you may not use this file except in 
 * compliance with the License.  You may obtain a copy of the License 
 * at http://www.mozilla.org/MPL/
 * 
 * Software distributed under the License is distributed on an 
 * "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or 
 * implied. See the License for the specific language governing rights 
 * and limitations under the License.
 * 
 * The Original Code is Web Photo Publisher.
 * 
 * The Initial Developer of the Original Code is Mark Roth.  Portions 
 * created by Mark Roth are Copyright (C) 2003 Mark Roth.  
 * All Rights Reserved.
 * 
 * Contributor(s) listed below.
 * </license>
 */

package com.javaimagealbum;

import com.javaimagealbum.util.BrowserControl;

/**
 * Introduces the user to the program
 *
 * @author  Mark Roth
 * @author  Mirko Actis Grosso
 */
public class IntroPanel 
    extends javax.swing.JPanel 
    implements WizardPanel
{

    /** Default serial version */
	private static final long serialVersionUID = 1L;
	
    /** Creates new form IntroPanel */
    public IntroPanel() {
        initComponents ();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblTitle = new javax.swing.JLabel();
        pnlDescription = new javax.swing.JPanel();
        tpDescription = new javax.swing.JTextPane();
        pnlNavigation = new javax.swing.JPanel();
        lblWebSite = new javax.swing.JLabel();
        btnWebSite = new javax.swing.JButton();
        lblSubmitBug = new javax.swing.JLabel();
        btnSubmitBug = new javax.swing.JButton();
        lblMailingList = new javax.swing.JLabel();
        btnMailingList = new javax.swing.JButton();
        pnlBottom = new javax.swing.JPanel();
        cbSkipIntro = new javax.swing.JCheckBox();

        setLayout(new java.awt.BorderLayout());

        setBackground(java.awt.Color.white);
        lblTitle.setFont(new java.awt.Font("SansSerif", 1, 14));
        lblTitle.setForeground(new java.awt.Color(0, 153, 153));
        lblTitle.setText("Java Image Album");
        lblTitle.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        add(lblTitle, java.awt.BorderLayout.NORTH);

        pnlDescription.setLayout(new java.awt.BorderLayout());

        pnlDescription.setBackground(java.awt.Color.white);
        pnlDescription.setAlignmentX(0.0F);
        pnlDescription.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        pnlDescription.setMinimumSize(new java.awt.Dimension(132, 25));
        pnlDescription.setPreferredSize(new java.awt.Dimension(544, 200));
        tpDescription.setEditable(false);
        tpDescription.setFont(new java.awt.Font("SansSerif", 0, 12));
        tpDescription.setText(java.util.ResourceBundle.getBundle("com/javaimagealbum/resources/Resource").getString("INTRO_PANEL_DESCRIPTION"));
        tpDescription.setAlignmentX(0.0F);
        tpDescription.setMinimumSize(new java.awt.Dimension(544, 100));
        tpDescription.setPreferredSize(new java.awt.Dimension(544, 100));
        tpDescription.setRequestFocusEnabled(false);
        pnlDescription.add(tpDescription, java.awt.BorderLayout.NORTH);

        pnlNavigation.setLayout(new java.awt.GridBagLayout());

        pnlNavigation.setBackground(java.awt.Color.white);
        pnlNavigation.setAlignmentX(0.0F);
        pnlNavigation.setFont(new java.awt.Font("SansSerif", 0, 12));
        pnlNavigation.setPreferredSize(new java.awt.Dimension(544, 70));
        lblWebSite.setFont(new java.awt.Font("SansSerif", 0, 12));
        lblWebSite.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblWebSite.setText(java.util.ResourceBundle.getBundle("com/javaimagealbum/resources/Resource").getString("LBL_WEB_SITE"));
        lblWebSite.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        lblWebSite.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        lblWebSite.setMinimumSize(new java.awt.Dimension(275, 23));
        lblWebSite.setPreferredSize(new java.awt.Dimension(500, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        pnlNavigation.add(lblWebSite, gridBagConstraints);

        btnWebSite.setText(java.util.ResourceBundle.getBundle("com/javaimagealbum/resources/Resource").getString("WEB_SITE"));
        btnWebSite.setMaximumSize(new java.awt.Dimension(90, 23));
        btnWebSite.setMinimumSize(new java.awt.Dimension(90, 23));
        btnWebSite.setPreferredSize(new java.awt.Dimension(90, 23));
        btnWebSite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnWebSiteMouseClicked(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        pnlNavigation.add(btnWebSite, gridBagConstraints);

        lblSubmitBug.setFont(new java.awt.Font("SansSerif", 0, 12));
        lblSubmitBug.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSubmitBug.setText(java.util.ResourceBundle.getBundle("com/javaimagealbum/resources/Resource").getString("LBL_SUBMIT_BUG"));
        lblSubmitBug.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        lblSubmitBug.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        lblSubmitBug.setMinimumSize(new java.awt.Dimension(275, 23));
        lblSubmitBug.setPreferredSize(new java.awt.Dimension(500, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        pnlNavigation.add(lblSubmitBug, gridBagConstraints);

        btnSubmitBug.setText(java.util.ResourceBundle.getBundle("com/javaimagealbum/resources/Resource").getString("SUBMIT_BUG"));
        btnSubmitBug.setMaximumSize(new java.awt.Dimension(90, 23));
        btnSubmitBug.setMinimumSize(new java.awt.Dimension(90, 23));
        btnSubmitBug.setPreferredSize(new java.awt.Dimension(90, 23));
        btnSubmitBug.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSubmitBugMouseClicked(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        pnlNavigation.add(btnSubmitBug, gridBagConstraints);

        lblMailingList.setFont(new java.awt.Font("SansSerif", 0, 12));
        lblMailingList.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMailingList.setText(java.util.ResourceBundle.getBundle("com/javaimagealbum/resources/Resource").getString("LBL_MAILING_LIST"));
        lblMailingList.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        lblMailingList.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        lblMailingList.setMinimumSize(new java.awt.Dimension(275, 23));
        lblMailingList.setPreferredSize(new java.awt.Dimension(500, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        pnlNavigation.add(lblMailingList, gridBagConstraints);

        btnMailingList.setText(java.util.ResourceBundle.getBundle("com/javaimagealbum/resources/Resource").getString("MAILING_LIST"));
        btnMailingList.setMaximumSize(new java.awt.Dimension(90, 23));
        btnMailingList.setMinimumSize(new java.awt.Dimension(90, 23));
        btnMailingList.setPreferredSize(new java.awt.Dimension(90, 23));
        btnMailingList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMailingListMouseClicked(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        pnlNavigation.add(btnMailingList, gridBagConstraints);

        pnlDescription.add(pnlNavigation, java.awt.BorderLayout.CENTER);

        add(pnlDescription, java.awt.BorderLayout.CENTER);

        pnlBottom.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        pnlBottom.setBackground(java.awt.Color.white);
        cbSkipIntro.setBackground(java.awt.Color.white);
        cbSkipIntro.setFont(new java.awt.Font("SansSerif", 0, 12));
        cbSkipIntro.setMnemonic('d');
        cbSkipIntro.setText(java.util.ResourceBundle.getBundle("com/javaimagealbum/resources/Resource").getString("DONT_SHOW_INTRO"));
        cbSkipIntro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSkipIntroActionPerformed(evt);
            }
        });

        pnlBottom.add(cbSkipIntro);

        add(pnlBottom, java.awt.BorderLayout.SOUTH);

    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitBugMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmitBugMouseClicked
        BrowserControl.displayURL(Constants.SUBMIT_BUG);
    }//GEN-LAST:event_btnSubmitBugMouseClicked

    private void btnMailingListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMailingListMouseClicked
        BrowserControl.displayURL(Constants.MAIL_LIST);
    }//GEN-LAST:event_btnMailingListMouseClicked

    private void btnWebSiteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnWebSiteMouseClicked
        BrowserControl.displayURL(Constants.HOSTING_URL);
    }//GEN-LAST:event_btnWebSiteMouseClicked

    private void cbSkipIntroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSkipIntroActionPerformed
        Settings.getInstance().setProperty( Constants.SKIP_INTRO, 
            "" + cbSkipIntro.isSelected() );
    }//GEN-LAST:event_cbSkipIntroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMailingList;
    private javax.swing.JButton btnSubmitBug;
    private javax.swing.JButton btnWebSite;
    private javax.swing.JCheckBox cbSkipIntro;
    private javax.swing.JLabel lblMailingList;
    private javax.swing.JLabel lblSubmitBug;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblWebSite;
    private javax.swing.JPanel pnlBottom;
    private javax.swing.JPanel pnlDescription;
    private javax.swing.JPanel pnlNavigation;
    private javax.swing.JTextPane tpDescription;
    // End of variables declaration//GEN-END:variables

    /** Returns true if all required data was filled in for this panel.
     */
    public boolean isSatisfied() {
        return true;
    }

    /** Called when the panel is shown to the user
     */
    public void showPanel() {
    }

    /** Called when the panel is hidden from the user
     */
    public void hidePanel(boolean forwardDirection) throws CannotChangePanelException {
    }
}
