/*
 * <license>
 * The contents of this file are subject to the Mozilla Public License 
 * Version 1.1 (the "License"); you may not use this file except in 
 * compliance with the License.  You may obtain a copy of the License 
 * at http://www.mozilla.org/MPL/
 * 
 * Software distributed under the License is distributed on an 
 * "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or 
 * implied. See the License for the specific language governing rights 
 * and limitations under the License.
 * 
 * The Original Code is Web Photo Publisher.
 * 
 * The Initial Developer of the Original Code is Mark Roth.  Portions 
 * created by Mark Roth are Copyright (C) 2003 Mark Roth.  
 * All Rights Reserved.
 * 
 * Contributor(s) listed below.
 * </license>
 */

package com.javaimagealbum;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.ResourceBundle;

import javax.swing.JOptionPane;

import com.javaimagealbum.resources.ResourceFactory;

/**
 * Dialog that displays the license agreement for this application.
 * Asks the user to agree or disagree.  The license file is retrieved from
 * the JAR file for the application in /LICENSE.txt and the status can
 * be queried with getAgree().
 *
 * @author  mroth
 * @author  Mirko Actis
 */
public class LicenseAgreementDialog extends javax.swing.JDialog {
    static ResourceBundle res = ResourceFactory.getBundle();
    static ResourceBundle resM = ResourceFactory.getMnemonicBundle();

    /** Location of the license file */
    private static final String LICENSE_FILE = "/LICENSE.txt";
    
    /** Creates new form LicenseAgreementDialog */
    public LicenseAgreementDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        try {
            StringBuffer license = new StringBuffer();
            BufferedReader in = new BufferedReader( new InputStreamReader(
                getClass().getResourceAsStream( LICENSE_FILE ) ) );
            String line;
            while( (line = in.readLine()) != null ) {
                license.append( line + "\n" );
            }
            in.close();
            taAgreement.setText( license.toString() );
        }
        catch( IOException e ) {
            JOptionPane.showMessageDialog( null, 
                "No license file found.  Aborting.", 
                "No License Found", JOptionPane.ERROR_MESSAGE );
            System.exit( 1 );
        }
        catch( NullPointerException e ) {
            JOptionPane.showMessageDialog( null, 
                "No license file found.  Aborting.", 
                "No License Found", JOptionPane.ERROR_MESSAGE );
            System.exit( 1 );
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        pnlDialog = new javax.swing.JPanel();
        pnlButtons = new javax.swing.JPanel();
        btnNoAgree = new javax.swing.JButton();
        btnAgree = new javax.swing.JButton();
        pnlInstructions = new javax.swing.JPanel();
        lblLicenseAgreement = new javax.swing.JLabel();
        lblInstructions1 = new javax.swing.JLabel();
        lblInstructions2 = new javax.swing.JLabel();
        pnlCenter = new javax.swing.JPanel();
        pnlAgreement = new javax.swing.JPanel();
        spAgreement = new javax.swing.JScrollPane();
        taAgreement = new javax.swing.JTextArea();
        lblAgreeQuestion = new javax.swing.JLabel();
        lblDoNotAgreeDef = new javax.swing.JLabel();
        lblAgreeDef = new javax.swing.JLabel();

        setTitle(Constants.APP_NAME+" - License Agreement");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        pnlDialog.setLayout(new java.awt.BorderLayout());

        pnlDialog.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(5, 5, 5, 5)));
        pnlButtons.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnNoAgree.setFont(new java.awt.Font("SansSerif", 0, 12));
        btnNoAgree.setMnemonic(resM.getString("DontAgree").charAt(0));
        btnNoAgree.setText(res.getString("DONT_AGREE"));
        btnNoAgree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoAgreeActionPerformed(evt);
            }
        });

        pnlButtons.add(btnNoAgree);

        btnAgree.setFont(new java.awt.Font("SansSerif", 0, 12));
        btnAgree.setMnemonic(resM.getString("Agree").charAt(0));
        btnAgree.setText(res.getString("AGREE"));
        btnAgree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgreeActionPerformed(evt);
            }
        });

        pnlButtons.add(btnAgree);

        pnlDialog.add(pnlButtons, java.awt.BorderLayout.SOUTH);

        pnlInstructions.setLayout(new java.awt.GridBagLayout());

        lblLicenseAgreement.setFont(new java.awt.Font("SansSerif", 1, 14));
        lblLicenseAgreement.setText("License Agreement");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        pnlInstructions.add(lblLicenseAgreement, gridBagConstraints);

        lblInstructions1.setFont(new java.awt.Font("SansSerif", 0, 12));
        lblInstructions1.setText("Please read the following License Agreement before continuing.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        pnlInstructions.add(lblInstructions1, gridBagConstraints);

        lblInstructions2.setFont(new java.awt.Font("SansSerif", 0, 12));
        lblInstructions2.setText("Use the scroll bar to view the rest of the agreement.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        pnlInstructions.add(lblInstructions2, gridBagConstraints);

        pnlDialog.add(pnlInstructions, java.awt.BorderLayout.NORTH);

        pnlCenter.setLayout(new java.awt.GridBagLayout());

        pnlAgreement.setLayout(new java.awt.GridLayout(1, 1));

        taAgreement.setColumns(40);
        taAgreement.setEditable(false);
        taAgreement.setFont(new java.awt.Font("SansSerif", 0, 12));
        taAgreement.setLineWrap(true);
        taAgreement.setRows(12);
        taAgreement.setWrapStyleWord(true);
        taAgreement.setAutoscrolls(false);
        spAgreement.setViewportView(taAgreement);

        pnlAgreement.add(spAgreement);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        pnlCenter.add(pnlAgreement, gridBagConstraints);

        lblAgreeQuestion.setFont(new java.awt.Font("SansSerif", 0, 12));
        lblAgreeQuestion.setText("Do you agree to the terms of the preceding License Agreement?");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        pnlCenter.add(lblAgreeQuestion, gridBagConstraints);

        lblDoNotAgreeDef.setFont(new java.awt.Font("SansSerif", 0, 12));
        lblDoNotAgreeDef.setText("If you choose \"I Do Not Agree\" the program will close.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        pnlCenter.add(lblDoNotAgreeDef, gridBagConstraints);

        lblAgreeDef.setFont(new java.awt.Font("SansSerif", 0, 12));
        lblAgreeDef.setText("To use this program, you must choose \"I Agree.\"");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        pnlCenter.add(lblAgreeDef, gridBagConstraints);

        pnlDialog.add(pnlCenter, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlDialog, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    private void btnAgreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgreeActionPerformed
        agree = true;
        dispose();
    }//GEN-LAST:event_btnAgreeActionPerformed

    private void btnNoAgreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoAgreeActionPerformed
        agree = false;
        dispose();
    }//GEN-LAST:event_btnNoAgreeActionPerformed

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        new LicenseAgreementDialog(new javax.swing.JFrame(), true).show();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgree;
    private javax.swing.JButton btnNoAgree;
    private javax.swing.JLabel lblAgreeDef;
    private javax.swing.JLabel lblAgreeQuestion;
    private javax.swing.JLabel lblDoNotAgreeDef;
    private javax.swing.JLabel lblInstructions1;
    private javax.swing.JLabel lblInstructions2;
    private javax.swing.JLabel lblLicenseAgreement;
    private javax.swing.JPanel pnlAgreement;
    private javax.swing.JPanel pnlButtons;
    private javax.swing.JPanel pnlCenter;
    private javax.swing.JPanel pnlDialog;
    private javax.swing.JPanel pnlInstructions;
    private javax.swing.JScrollPane spAgreement;
    private javax.swing.JTextArea taAgreement;
    // End of variables declaration//GEN-END:variables

    
    private boolean agree = false;
    
    public boolean getAgree() {
        return this.agree;
    }
}
